name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for filing a bug
        Please include the exact MCP tool invocations (`ssh_plan`, `ssh_run`, etc.) so we can reproduce the issue.
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Provide a concise summary of the problem.
      placeholder: The orchestrator returned X when I expected Y...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: List each MCP tool call and include command arguments + outputs.
      placeholder: |
        1. `ssh_plan alias="web-1" command="uptime"`
        2. `ssh_run alias="web-1" command="uptime"`
        3. Error output / denial message
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you thought would happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Describe what actually happened (include error text if possible).
    validations:
      required: true
  - type: checkboxes
    id: prechecks
    attributes:
      label: Pre-checks
      description: Run through these before filing so we can debug faster.
      options:
        - label: I confirmed `ssh_plan` reports the command should be allowed.
        - label: I reran `ssh_reload_config` after editing any YAML.
        - label: I verified the host alias/tag exists in `servers.yml`.
        - label: I confirmed my `known_hosts` entry matches the target host.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include OS, Docker version, MCP client, and orchestrator version.
      placeholder: |
        OS: macOS 15.0
        Docker: Docker Desktop 4.29.0
        MCP SSH Orchestrator: 1.0.0
        MCP client: Cursor
        Python version (if local): 3.11.8
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Sanitized configuration
      description: Redact anything sensitive. Include only the sections that matter.
      placeholder: |
        ```yaml
        # servers.yml
        hosts:
          - alias: "example"
            host: "10.0.0.1"
            port: 22
            credentials: "example_creds"
            tags: ["test"]

        # policy.yml
        limits:
          max_seconds: 60
          max_output_bytes: 1048576
        ```
      render: markdown
  - type: textarea
    id: logs
    attributes:
      label: Logs / stderr excerpts
      description: Paste relevant error messages or audit log snippets (sanitized).
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else we should know?
  - type: markdown
    attributes:
      value: |
        **Security Note**
        Do **not** include sensitive information (IPs, credentials, secrets). Sanitize all snippets before posting.
