name: Documentation Issue
description: Report a documentation problem or suggest improvements
title: "[DOCS] "
labels:
  - documentation
  - needs-triage
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Type of issue
      multiple: true
      options:
        - Incorrect information
        - Missing information
        - Unclear explanation
        - Outdated content
        - Formatting issue
        - Broken links
        - Missing examples
        - Other
  - type: checkboxes
    id: affected-docs
    attributes:
      label: Affected documentation
      options:
        - label: README.md
        - label: SECURITY.md
        - label: docs/wiki (specify file below)
        - label: compose/README.md or setup.sh
        - label: examples/*.yml
        - label: `.github` templates
        - label: Code comments/docstrings
        - label: Other (describe below)
  - type: textarea
    id: location
    attributes:
      label: File / section
      description: Provide the exact path or wiki link (e.g., `docs/wiki/14-FAQ.md#support`).
    validations:
      required: true
  - type: textarea
    id: current-text
    attributes:
      label: Current documentation
      description: Quote the problematic text (sanitized).
      render: markdown
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Explain why the documentation is wrong or insufficient. Call out whether it references unsupported/future functionality or contradicts the code.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
      description: Provide the wording or structure you recommend.
      render: markdown
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mention the affected user level, use case, and priority (Low/Medium/High).
  - type: textarea
    id: related
    attributes:
      label: Related issues or discussions
      description: Link any relevant issues, PRs, or external references.
  - type: markdown
    attributes:
      value: |
        **Note:** For code-related bugs, please use the bug report template instead.
