---
name: Documentation Issue
about: Report a documentation problem or suggest improvements
title: '[DOCS] '
labels: ['documentation', 'needs-triage']
assignees: ''
---

## Documentation Issue

## Type of Issue
- [ ] **Incorrect information**: The documentation contains wrong information
- [ ] **Missing information**: Important information is not documented
- [ ] **Unclear explanation**: The documentation is confusing or hard to understand
- [ ] **Outdated content**: The documentation is outdated and doesn't match current behavior
- [ ] **Formatting issue**: The documentation has formatting problems
- [ ] **Broken links**: Links in the documentation are broken
- [ ] **Missing examples**: More examples would be helpful
- [ ] **Other**: _______________

## Affected Documentation
Please specify which documentation is affected:
- [ ] README.md
- [ ] CONTRIBUTING.md
- [ ] docs/CONTRIBUTING.md
- [ ] docs/DOCKER_DESKTOP.md
- [ ] docs/LOCAL_DEVELOPMENT.md
- [ ] docs/SECURITY.md
- [ ] Example configuration files
- [ ] Code comments/docstrings
- [ ] Other: _______________

## Current Documentation
If reporting incorrect or unclear information, please quote the relevant section:

```markdown
[Paste the problematic documentation here]
```

## Problem Description
Describe what's wrong with the documentation or what's missing.

## Suggested Improvement
Describe how the documentation should be improved:

```markdown
[Paste your suggested improvement here]
```

## Additional Context
- **User level**: [Beginner/Intermediate/Advanced] - What level of user would be affected?
- **Use case**: Describe the specific use case or scenario where this documentation issue causes problems
- **Priority**: [Low/Medium/High] - How important is this documentation fix?

## Related Issues
Link any related issues:
- Related to #123
- Duplicate of #456

---

**Note**: For code-related issues, please use the bug report template instead.
