name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        ## Help us scope your idea
        Please describe the problem first, then the change you'd like to see. Tie everything back to existing MCP tools or YAML.
  - type: textarea
    id: summary
    attributes:
      label: Feature summary
      description: One paragraph describing the capability you need.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What workflow is blocked today? Who is impacted?
      placeholder: We're unable to ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Reference the MCP tool, prompt, or YAML file you expect will change.
      placeholder: Update `ssh_plan` to return ...
  - type: textarea
    id: security
    attributes:
      label: Security alignment
      description: Explain how this keeps the deny-by-default posture intact. List any new allow rules, network changes, or audit events required.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Existing workarounds, even if imperfect.
  - type: textarea
    id: use-cases
    attributes:
      label: Representative use cases
      description: Provide concrete command/tool examples that would benefit.
      placeholder: |
        1. Operator asks Cursor to ...
        2. MCP client calls `ssh_run_on_tag ...`
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
  - type: textarea
    id: implementation
    attributes:
      label: Implementation considerations
      description: Complexity, dependencies, or breaking changes we should know about (transport must remain stdio-only).
  - type: textarea
    id: additional
    attributes:
      label: Additional context / references
      description: Link related issues, designs, or screenshots.
